stages:
- test

test:
  image: golang:1.12
  stage: test
  artifacts:
    reports:
      junit: junit.xml

  script:
  - go get github.com/jstemmer/go-junit-report
  - go test ./... -v 2>&1 | tee >(go-junit-report > junit.xml)
  