stages:
- test

test:
  image: golang
  stage: test
  artifacts:
    reports:
      junit: junit.xml

  script:
  - go get -u github.com/jstemmer/go-junit-report
  - go test ./... -v 2>&1 | go-junit-report > junit.xml
  